[constants]
spdk_root = '/opt/spdk'
vcpkg_root = 'vcpkg_installed/x64-linux'

[built-in options]
buildtype = 'release'
pkg_config_path = [spdk_root + '/build/lib/pkgconfig']
; pkg_config_path = [vcpkg_root + '/lib/pkgconfig', spdk_root + '/build/lib/pkgconfig']
; cmake_prefix_path = [vcpkg_root + '/share']

[properties]
spdk_include = spdk_root + '/include/'
spdk_build_include = spdk_root + '/build/include/'
spdk_build_lib = spdk_root + '/build/lib/'
dpdk_build_lib = spdk_root + '/dpdk/build/lib/'
vcpkg_include = vcpkg_root + '/include/'