server {
    listen 8080;
    server_name localhost;
    root /data;

    location / {
        autoindex on;
        autoindex_format json;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        add_header Access-Control-Allow-Headers "*";
    }
}
