apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      allowedHosts:
        - http://csv-server:8080
